config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  post '/countries/:country_id/regions', to: 'regions#createId'
  post '/regions/:region_id/cities', to: 'cities#createId'
  post '/cities/:city_id/hostels', to: 'hostels#createId'
 
  resources :countries do
  	resources :regions, only: [:index, :new, :destroy] do
    end
  end

  resources :regions do
  	resources :cities, only: [:index, :new, :destroy]
  end

  resources :cities do
    resources :hostels, only: [:index, :new, :destroy]
  end
  
  resources :hostels
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :hostels, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :regions, dependent: :destroy
end

app/models/hostel.rb
class Hostel < ApplicationRecord
  belongs_to :city
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  has_many :cities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def index
		@cities = City.all
	end

	def show
		@city = City.find(params[:id])
	end

	def new
		@city = City.new
	end

	def edit
		@city = City.find(params[:id])
	end

	def update
		@city = City.find(params[:id])

		if @city.update(city_params)
			redirect_to @city
		else
			render 'edit'
		end
	end

	def create
		if (city_params[:region_id] != "") then
			@region = Region.find(city_params[:region_id])
			@city = @region.cities.create(city_params)

			redirect_back(fallback_location: root_path)
		end
	end

	def createId
		@region = Region.find(params[:region_id])
		@city = @region.cities.create(city_params)

		redirect_back(fallback_location: root_path)
	end

	def destroy
		@city = City.find(params[:id])
		if (@city.hostels.count == 0) then
			@city.destroy
			redirect_back(fallback_location: root_path)
		end

	end

	private
	def city_params
		params.require(:city).permit(:region_id, :name)
	end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

	def index
		@countries = Country.all
	end

	def show
		@country = Country.find(params[:id])
	end

	def new
		@country = Country.new
	end

	def edit
		@country = Country.find(params[:id])
	end

	def create
		@country = Country.new(country_params)

		if @country.save
			redirect_to @country
		else
			render 'new'
		end
	end

	def update
		@country = Country.find(params[:id])

		if @country.update(country_params)
			redirect_to @country
		else
			render 'edit'
		end
	end

	def destroy
		@country = Country.find(params[:id])
		if (@country.regions.count == 0) then
			@country.destroy
			redirect_back(fallback_location: root_path)
		end
	end

	private
	def country_params
		params.require(:country).permit(:name)
	end
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController

	def index
		@hostels = Hostel.all
	end

	def show
		@hostel = Hostel.find(params[:id])
	end

	def new
		@hostel = Hostel.new
	end

	def edit
		@hostel = Hostel.find(params[:id])
	end

	def update
		@hostel = Hostel.find(params[:id])

		if @hostel.update(hostel_params)
			redirect_to @hostel
		else
			render 'edit'
		end
	end

	def create
		if (hostel_params[:city_id] != "") then
			@city = City.find(hostel_params[:city_id])
			@hostel = @city.hostels.create(hostel_params)

			redirect_back(fallback_location: root_path)
		end
	end

	def createId
		@city = City.find(params[:city_id])
		@hostel = @city.hostels.create(hostel_params)

		redirect_back(fallback_location: root_path)
	end

	def destroy
		@hostel = Hostel.find(params[:id])
		@hostel.destroy

		redirect_back(fallback_location: root_path)
	end

	private
	def hostel_params
		params.require(:hostel).permit(:city_id, :name)
	end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

	def index
		@regions = Region.all
	end

	def show
		@region = Region.find(params[:id])
	end

	def new
		@region = Region.new
	end

	def edit
		@region = Region.find(params[:id])
	end

	def update
		@region = Region.find(params[:id])

		if @region.update(region_params)
			redirect_to @region
		else
			render 'edit'
		end
	end

	def create
		if (region_params[:country_id] != "") then
			@country = Country.find(region_params[:country_id])
			@region = @country.regions.create(region_params)

			redirect_back(fallback_location: root_path)
		end
	end

	def createId

		@country = Country.find(params[:country_id])			
		@region = @country.regions.create(region_params)

		redirect_back(fallback_location: root_path)
	end

	def destroy
		@region = Region.find(params[:id])
		if (@region.cities.count == 0) then
			@region.destroy
			redirect_back(fallback_location: root_path)
		end

	end

	private
	def region_params
		params.require(:region).permit(:country_id, :name)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_city.html.erb
<tr>
  <td><%= city.name %></td>
  <td><%= link_to 'Show', city_path(city), :class => "pure-button" %></td>
  <td><%= link_to 'Edit', edit_city_path(city), :class => "pure-button" %></td>
  <td><%= link_to 'Destroy city', [city.region, city],
               method: :delete,
               onclick: "isGood(#{city.hostels.count});", 
               :class => "pure-button" %></td>

</tr>

app/views/cities/_form.html.erb
<%= form_with model: @city, local: true , :class => "pure-form pure-form-stacked" do |form| %>
 
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@city.errors.count, "error") %> prohibited
        this city from being saved:
      </h2>
      <ul>
        <% @city.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <p>
    <%= form.label :Region %>
    <%= form.select(:region_id) do %>
        <% if (form.object.region_id == nil) %>
          <option value="" selected>Please choose</option>
        <% end %>
        <%= options_from_collection_for_select(Region.all, :id, :name, :selected => form.object.region_id) %>
    <% end %>
  </p>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button" %>
  </p>
 
<% end %>

app/views/cities/_formC.html.erb
<%= form_with(model: [ @region, @region.cities.build ], :class => "pure-form pure-form-stacked") do |form| %>
 
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button" %>
  </p>
 
<% end %>

app/views/cities/edit.html.erb
<h1>Edit city</h1>

<%= render 'form' %>
 
<%= link_to 'Back', cities_path, :class => "pure-button" %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>
<%= link_to 'New city', new_city_path, :class => "green-button pure-button" %>
<br>
<br>
<table class="pure-table pure-table-horizontal">
  <tr>
    <th>Name</th>
    <th>Region</th>
    <th>Country</th>
    <th colspan="3"></th>
  </tr>
 
  <% @cities.each do |city| %>
    <tr>
      <td><%= city.name %></td>
      <td><%= city.region.name %></td>
      <td><%= city.region.country.name %></td>
      <td><%= link_to 'Show', city_path(city), :class => "pure-button"%></td>
      <td><%= link_to 'Edit', edit_city_path(city), :class => "pure-button" %></td>
      <td><%= link_to 'Destroy', city_path(city),
              method: :delete,
              :class => "pure-button",
              onclick: "isGood(#{city.hostels.count});"%></td>
    </tr>
  <% end %>
</table>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>
 
<%= link_to 'Back', cities_path, :class => "pure-button"%>

app/views/cities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<h2>Hostels</h2>
<% if (@city.hostels.count > 0) then%>
<table class="pure-table pure-table-horizontal">
	<tr>
		<th>Name</th>
		<th colspan="3"></th>
	</tr>
	<%= render @city.hostels %>
</table>
<% else %>
	No regions
<% end %>
 
<h2>Add a hostel:</h2>
<%= render 'hostels/formC' %>

 <%= link_to 'Edit', edit_city_path(@city), :class => "pure-button" %> |
<%= link_to 'Back', cities_path, :class => "pure-button" %>

app/views/countries/_form.html.erb
<%= form_with model: @country, local: true, :class => "pure-form pure-form-stacked" do |form| %>
 
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@country.errors.count, "error") %> prohibited
        this country from being saved:
      </h2>
      <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button" %>
  </p>
 
<% end %>

app/views/countries/edit.html.erb
<h1>Edit Country</h1>

<%= render 'form' %>
 
<%= link_to 'Back', countries_path, :class => "pure-button"%>

app/views/countries/index.html.erb
<h1>Listing Countries</h1>
<%= link_to 'New country', new_country_path, :class => "green-button pure-button" %>
<br>
<br>
<table class="pure-table pure-table-horizontal">
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
 
  <% @countries.each do |country| %>
    <tr>
      <td><%= country.name %></td>
      <td><%= link_to 'Show', country_path(country), :class => "pure-button" %></td>
      <td><%= link_to 'Edit', edit_country_path(country), :class => "pure-button" %></td>
      <td><%= link_to 'Destroy', country_path(country),
              method: :delete,
              onclick: "isGood(#{country.regions.count});", 
              :class => "pure-button" %></td>
    </tr>
  <% end %>
</table>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form' %>
 
<%= link_to 'Back', countries_path, :class => "pure-button"%>

app/views/countries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>
<h2>Regions</h2>
<% if (@country.regions.count > 0) then%>
<table class="pure-table pure-table-horizontal">
	<tr>
		<th>Name</th>
		<th colspan="3"></th>
	</tr>
	<%= render @country.regions %>
</table>
<% else %>
	No regions
<% end %>
 
 
<h2>Add a region:</h2>
<%= render 'regions/createId' %>

 <%= link_to 'Edit', edit_country_path(@country), :class => "pure-button" %> |
<%= link_to 'Back', countries_path, :class => "pure-button" %>

app/views/hostels/_form.html.erb
<%= form_with model: @hostel, local: true, :class => "pure-form pure-form-stacked" do |form| %>
 
  <% if @hostel.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@hostel.errors.count, "error") %> prohibited
        this hostel from being saved:
      </h2>
      <ul>
        <% @hostel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <p>
    <%= form.label :City %>
    <%= form.select(:city_id) do %>
        <% if (form.object.city_id == nil) then %>
          <option value="" selected>Please choose</option>
        <% end %>
        <%= options_from_collection_for_select(City.all, :id, :name, :selected => form.object.city_id) %>
    <% end %>
  </p>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button"%>
  </p>
 
<% end %>

app/views/hostels/_formC.html.erb
<%= form_with(model: [ @city, @city.hostels.build ], :class => "pure-form pure-form-stacked") do |form| %>
 
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button" %>
  </p>
 
<% end %>

app/views/hostels/_hostel.html.erb
<tr>
  <td><%= hostel.name %></td>
  <td><%= link_to 'Show', hostel_path(hostel), :class => "pure-button" %></td>
  <td><%= link_to 'Edit', edit_hostel_path(hostel), :class => "pure-button" %></td>
  <td><%= link_to 'Destroy hostel', [hostel.city, hostel],
               method: :delete,
               data: { confirm: 'Are you sure?'}, 
               :class => "pure-button" %></td>

</tr>

app/views/hostels/edit.html.erb
<h1>Edit hostel</h1>

<%= render 'form' %>
 
<%= link_to 'Back', hostels_path, :class => "pure-button" %>

app/views/hostels/index.html.erb
<h1>Listing hostels</h1>
<%= link_to 'New hostel', new_hostel_path, :class => "green-button pure-button" %>
<br>
<br>
<table class="pure-table pure-table-horizontal">
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Region</th>
    <th>Country</th>
    <th colspan="3"></th>
  </tr>
 
  <% @hostels.each do |hostel| %>
    <tr>
      <td><%= hostel.name %></td>
      <td><%= hostel.city.name %></td>
      <td><%= hostel.city.region.name %></td>
      <td><%= hostel.city.region.country.name %></td>
      <td><%= link_to 'Show', hostel_path(hostel), :class => "pure-button" %></td>
      <td><%= link_to 'Edit', edit_hostel_path(hostel), :class => "pure-button" %></td>
      <td><%= link_to 'Destroy', hostel_path(hostel),
              method: :delete,
              data: { confirm: 'Are you sure?' }, 
              :class => "pure-button" %></td>
    </tr>
  <% end %>
</table>

app/views/hostels/new.html.erb
<h1>New hostel</h1>

<%= render 'form' %>
 
<%= link_to 'Back', hostels_path, :class => "pure-button" %>

app/views/hostels/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @hostel.name %>
</p>


 <%= link_to 'Edit', edit_hostel_path(@hostel), :class => "pure-button"%> |
<%= link_to 'Back', hostels_path, :class => "pure-button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hostels</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
     strong,
	   h3,
	   h2,
	   h1 { 
	    color: rgb(28, 184, 65);
	   }
	   th {
	    color: rgb(28, 184, 65);
	   }
  </style>
  <%= render 'welcome/base' %>
  </head>

  <body>
  <%= render 'welcome/menu' %>

<div class="pure-g">
    <div class="pure-u-1-12"></div>
    <div class="pure-u-11-12">
      <style scoped>
        .green-button {
            background: rgb(28, 184, 65); /* this is a green */
        }
      </style>
	    <%= yield %>
	    </div>
	    </div>
      <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/regions/_createId.html.erb
<%= form_with(model: [ @country, @country.regions.build ], :class => "pure-form pure-form-stacked") do |form| %>
 
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button" %>
  </p>
 
<% end %>

app/views/regions/_form.html.erb
<%= form_with model: @region, local: true, :class => "pure-form pure-form-stacked" do |form| %>
 
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@region.errors.count, "error") %> prohibited
        this region from being saved:
      </h2>
      <ul>
        <% @region.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :Country %>
    <%= form.select(:country_id) do %>
        <% if (form.object.country_id == nil) %>
          <option value="" selected>Please choose</option>
        <% end %>
        <%= options_from_collection_for_select(Country.all, :id, :name, :selected => form.object.country_id) %>
    <% end %>
  </p>


  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.button :class => "pure-button" %>
  </p>
 
<% end %>

app/views/regions/_region.html.erb
<tr>
  <td><%= region.name %></td>
  <td><%= link_to 'Show', region_path(region), :class => "pure-button" %></td>
  <td><%= link_to 'Edit', edit_region_path(region), :class => "pure-button" %></td>
  <td><%= link_to 'Destroy Region', [region.country, region],
               method: :delete,
               onclick: "isGood(#{region.cities.count});", 
               :class => "pure-button" %></td>

</tr>

app/views/regions/edit.html.erb
<h1>Edit Region</h1>

<%= render 'form' %>
 
<%= link_to 'Back', regions_path, :class => "pure-button"%>

app/views/regions/index.html.erb
<h1>Listing Regions</h1>
<%= link_to 'New region', new_region_path, :class => "green-button pure-button"%>
<br>
<br>
<table class="pure-table pure-table-horizontal">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th colspan="3"></th>
  </tr>
 
  <% @regions.each do |region| %>
    <tr>
      <td><%= region.name %></td>
      <td><%= region.country.name %></td>
      <td><%= link_to 'Show', region_path(region), :class => "pure-button" %></td>
      <td><%= link_to 'Edit', edit_region_path(region), :class => "pure-button" %></td>
      <td><%= link_to 'Destroy', region_path(region),
              method: :delete,
              onclick: "isGood(#{region.cities.count});", 
              :class => "pure-button" %></td>
    </tr>
  <% end %>
</table>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render 'form' %>
 
<%= link_to 'Back', regions_path, :class => "pure-button" %>

app/views/regions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<h2>Cities</h2>
<% if (@region.cities.count > 0) then%>
<table class="pure-table pure-table-horizontal">
	<tr>
		<th>Name</th>
		<th colspan="3"></th>
	</tr>
	<%= render @region.cities %>
</table>
<% else %>
	No cities
<% end %>
 
<h2>Add a city:</h2>
<%= render 'cities/formC' %>

 <%= link_to 'Edit', edit_region_path(@region) , :class => "pure-button"%> |
<%= link_to 'Back', regions_path , :class => "pure-button"%>

app/views/welcome/_base.html.erb
<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/welcome/_menu.html.erb
<div class="pure-menu pure-menu-horizontal">
    <span class="pure-menu-heading pure-menu-link">Menu</span>
    <ul class="pure-menu-list">
        <li class="pure-menu-item">
            <%= link_to 'Start page', controller: 'welcome' %>
        </li>
        <li class="pure-menu-item">
            <%= link_to 'Countries', controller: 'countries' %>
        </li>
        <li class="pure-menu-item">
    	   <%= link_to 'Regions', controller: 'regions' %>
    	</li>
        <li class="pure-menu-item">
    	   <%= link_to 'Cities', controller: 'cities' %>
    	</li>
        <li class="pure-menu-item">
    	   <%= link_to 'Hostels', controller: 'hostels' %>
    	</li>
	<ul>
</div>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>